Feature/5 one time sync
ovelartelius/episerver-env-sync pull request #8
Opened 2020-11-11 23:21 UTC by ovelartelius

2020-11-12 14:45 UTC, LinusEkstrom requested changes

2020-11-12 14:53 UTC, ovelartelius commented on Addon.Episerver.EnvironmentSynchronizer/InitializationModule/SynchronizationInitializationModule.cs
> +				if (!runInitialization) return;
Agree. I blame ReSharper :)

2020-11-13 07:59 UTC, ovelartelius commented on Addon.Episerver.EnvironmentSynchronizer/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.1.*")]
Maybe not. I will lower it to 0.2.1

2020-11-13 08:08 UTC, ovelartelius commented on Addon.Episerver.EnvironmentSynchronizer/Addon.Episerver.EnvironmentSynchronizer.csproj
> +    <Reference Include="EPiServer.Cms.Shell.UI, Version=11.1.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7, processorArchitecture=MSIL">
I played around with the idea to create one or more supporting admin pages. But dropped that. Maybe later if we have a good reason. Ref removed.

2020-11-13 08:29 UTC, ovelartelius commented on Addon.Episerver.EnvironmentSynchronizer/DynamicData/EnvironmentSynchronizationStore.cs
> +	public interface IEnvironmentSynchronizationStore
All interfaces a in there own file now.

2020-11-13 08:40 UTC, ovelartelius commented on Addon.Episever.EnvironmentSynchronizer.Test/app.config
> +      <dependentAssembly>
It is included in the Episerver.CMS.Core nuget package. Do you think we should remove just this reference?

2020-11-13 09:09 UTC, ovelartelius commented on Addon.Episerver.EnvironmentSynchronizer/DynamicData/EnvironmentSynchronizationFlag.cs
> +	public class EnvironmentSynchronizationFlag : ISerializable, IDynamicData
Renamed to *Stamp

2020-11-13 16:11 UTC, merged